### ISSUE TITLE
Set up publish to rubygems workflow

### ISSUE THREAD

**Issue by frankieroberto** [x-govuk/govuk-rspec-helpers#22]
We should set up a GitHub workflow which auto publishes to rubygems (when tagged?).

See [publish.yml](https://github.com/x-govuk/govuk-components/blob/main/.github/workflows/publish.yml) from the govuk-components repo for an example.

@peteryates would you mind helping with this?

**Comment by peteryates** [comment]
I'll gladly help.

Currently the form builder and components libraries are under my personal rubygems account, I think it will make sense to add a x-govuk one and I'll transfer those gems over to it.

Once that's done we can generate a token and paste the workflow.

**Comment by frankieroberto** [comment]
@peteryates good plan! We already have an x-gov org for npm publishing but not for rubygems I don’t think.

**Comment by frankieroberto** [comment]
@peteryates I think [the helpers](https://x-govuk.github.io/govuk-rspec-helpers/) now cover enough features for it to be worth doing an initial npm release, what do you think?   Could call it `0.1.0` maybe?  Then we could invite a few of the services using Rails to give it a try out?

**Comment by peteryates** [comment]
I just registered x-govuk on Rubygems, I'll raise a PR tomorrow with the necessary workflow.
